# QtClass Config
name: quanttide-tutorial-of-cloud-computing
title: 量潮云计算教程
author: 量潮科技
level: intermediate
stage: pre-alpha
category: tutorial
tags:
  - python
  - cloud_computing
# Jupyter Book Config
only_build_toc_files: true